### ISSUE TITLE
[help wanted] OAUTH device

### ISSUE THREAD

**Issue by DONSA** [vankasteelj/trakt.tv#11]
Hi,
I'm trying to use OAUTH device method but I don't really get how I can get the token after the get_codes() method is called and the user authenticates his device.
Do you have an implementation example that you can provide or extra information?

**Comment by vankasteelj** [comment]
Sure. The idea of Device Auth is to let the user do the job : just show him an URL (maybe a QR too, for fun) and give him a code to enter when he visits that url. The code shown in the readme does everything else (which is, fyi : checking with trakt every X seconds to see if the user got there and entered the right code, if he did, it imports tokens and authenticates the user).

```
// start oauth device flow
trakt.get_codes()
    .then(function (poll) {
        // SHOW HERE AN URL LINK FOR THE USER TO VISIT -> poll.verification_url
        // ALSO SHOW HIM THE CODE HE'LL NEED TO ENTER IN THE ABOVE URL -> poll.user_code
        // for example:
       $('.popup').show();
       $('.popup .verif').html('Please <a href="'+poll.verification_url+'">click here</a> to visit trakt.tv website');
       $('.popup .code').html('There, enter this code : '+poll.user_code);

        // this function will automatically poll trakt to see if user 
        // entered the code in the trakt website
        return trakt.poll_access(poll);
    })
    .catch(function (error)
        // Handles errors
        // specific error.message == 'Expired' will be thrown
        // in case the verification_url was not used in time
    });
```

I don't have an example of app using Device OAuth, but here's some implementations with traditionnal method : 
- https://github.com/jaruba/PowderPlayer/blob/react-polymer/src/components/Player/utils/trakt.js
- https://github.com/butterproject/butter-desktop/blob/master/src/app/lib/providers/trakttv.js#L435

**Comment by DONSA** [comment]
Thanks, I will give it a try.
