### ISSUE TITLE
The lib's dependencies on plugins could be improved

### ISSUE THREAD

**Issue by danbovey** [vankasteelj/trakt.tv#20]
Compiling this with Webpack gives the error

```
Warning in ./~/trakt.tv/trakt.js
66:29-44 Critical dependency: the request of a dependency is an expression
```

It's not exactly critical or broken, just a warning that the way you're importing plugins isn't the best way of doing it.

I think a better way of importing plugins (and which would nicely remove this warning 😉) would be to tell the user in the  docs to `require('trakt.tv-ondeck')` and then pass that to the `plugins` array when initializing.

I'll submit a PR if you think that's an alright change.

**Comment by vankasteelj** [comment]
You can, I wrote those plugins from scratch, you do however need to keep the `main.module` API in this lib and `module.main` calls in the plugins. Avoinding try/catch in the main module would be nice, even if it's a little less "easy" than just declaring it inside an array, it does make sense for a dev

**Comment by danbovey** [comment]
Yeah I like the developer experience of just declaring the plugins as strings but this feels way more stable:

```js
_plugins(plugins, options) {
    const errors = [];
    for (let name in plugins) {
        if (!plugins.hasOwnProperty(name)) continue;

        this[name] = plugins[name];
        this[name].init(this);
        this._debug('Trakt.tv ' + name + ' plugin loaded');
    }
}
```

```js
const trakt = new Trakt({
    client_id: <the_client_id>,
    client_secret: <the_client_secret>,
    plugins: {
        ondeck: require('trakt.tv-ondeck')
    }
});
```

**Comment by vankasteelj** [comment]
```
const trakt = new Trakt({
    client_id: <the_client_id>,
    client_secret: <the_client_secret>,
    plugins: {
        ondeck: require('trakt.tv-ondeck')
    }
});
```

This is nice, people can also not have to use the "trakt.tv-" prefix, even if nobody's developping plugins, it's still better. Like someone could want this :

```
new Trakt({
 plugins: {lolnope: require('trakt.tv-ondeck')}
});
```

and be able to call `trakt.lolnope` watcha' think?
