### ISSUE TITLE
reuse get_url() gives CSRF error

### ISSUE THREAD

**Issue by janpio** [vankasteelj/trakt.tv#24]
I managed to get a code and exchange it for a access_token. Unfortunately I uses the wrong user for that and have no data in the current account. So I thought I would quickly implement the logout functionality... that doesn't seem to exist!? 

How do I logout the current user or switch to another one?

**Comment by janpio** [comment]
Ok, I found `revoke_token()`. Unfortunately no Promise or other return value, how is this supposed to be used?

**Comment by vankasteelj** [comment]
It just sends the revoke token data to trakt, there is no response : http://docs.trakt.apiary.io/#reference/authentication-oauth/revoke-token/revoke-an-access_token and clears the local user information. You basically have a clean local api, as if you were to start from scratch again. It's instant. You can send revoke_token() and immediately start the flow over again

**Comment by janpio** [comment]
Yep, works. 

Only thing I stumbled over was that I had to call `trakt.get_url()` again - I had implemented that as class variable and tried to reuse it which then gave a "invalid CSRF" error. (The "protection" stuff could use some docs in general)

**Comment by janpio** [comment]
Ok, I might be missing something here: 
Even after revoke_token (and manually revoking my app's access to the account) I don't have to login again at trakt - the OAuth flow just redirects me through and gives me a code. I'm using this in an Ionic/Angular app on Android, is there a way to force a logout so I can actually switch users?

**Comment by janpio** [comment]
Seems to be the Browser being used is still logged in to trakt, so the next OAuth flow try will automatically redirect to the callback URI as long as I don't manually log out. Probably nothing for the API to do but for me to understand how to get rid of those :/

**Comment by vankasteelj** [comment]
I don't really know how CSRF works though, it's just there 'cause I followed the trakt docs, if you know what it is and how it works

**Comment by janpio** [comment]
Hm ok, will look into it later when I work on the code again. Right now I just use a new get_url() for every login attempt.

**Comment by vankasteelj** [comment]
I've looked into it, and it's indeed a protection. You can either use get_url() and set a random hexadecimal "state code" to prevent CSRF (read: https://www.wikiwand.com/en/Cross-site_request_forgery#/Prevention), or you can use only exchange_code without the csrf state with less security. It is stated "optional" in the docs.
