### ISSUE TITLE
Feature Request: isTokenExpired

### ISSUE THREAD

**Issue by janpio** [vankasteelj/trakt.tv#25]
It would be great if the library would a simple function to check if the access_token is expired and has to be refreshed.

**Comment by janpio** [comment]
Oh, seems as if `import_token` takes care of that already and there is not need for me to do that manually, correct?

https://github.com/vankasteelj/trakt.tv/blob/master/trakt.js#L349-L353

**Comment by vankasteelj** [comment]
that is correct, if you don't tamper with timestamps manually, there is no reason for you to check the validity of the token, the wrapper will take care of everything
