### ISSUE TITLE
Enhancement: Change "Supported Methods" to table, add data

### ISSUE THREAD

**Issue by janpio** [vankasteelj/trakt.tv#26]
If the "Supported Methods" were output as a [table](http://www.tablesgenerator.com/markdown_tables) a lot of additional data like API URI, Method and Auth could be output. This could greatly improve readability of the list.

**Comment by vankasteelj** [comment]
Feel free to make a snippet of something similar to the code used below the [supported method list](https://github.com/vankasteelj/trakt.tv/wiki/Supported-methods). It's just there as information, the important stuff is in the json document and on docs.trakt.apiary.io/

**Comment by janpio** [comment]
Yep, wasn't meant as "hey you maintainer, go do that" but more as a "I thought it would be nice, lets write it down to see if I have the time to tinker with that later" ;)

**Comment by vankasteelj** [comment]
how is this?
![brackets_2017-07-04_19-39-44](https://user-images.githubusercontent.com/12599850/27839305-8bd22fa6-60f0-11e7-8fd4-e13c2760682b.png)

**Comment by janpio** [comment]
Awesome!

**Comment by vankasteelj** [comment]
progressing

![brackets_2017-07-04_20-41-50](https://user-images.githubusercontent.com/12599850/27840433-35297e6c-60f9-11e7-8f7d-fc60f691a70c.png)

**Comment by janpio** [comment]
Now it's actually pretty :)

**Comment by vankasteelj** [comment]
https://github.com/vankasteelj/trakt.tv/blob/master/docs
