### ISSUE TITLE
`pagination` object stays empty although returned from API

### ISSUE THREAD

**Issue by janpio** [vankasteelj/trakt.tv#28]
This is my call:

```
this.trakt.sync.history.get({
  pagination: true
});
```

It returns the pagination data in the header as it should:
![response](https://user-images.githubusercontent.com/183673/27835573-cc1fe298-60db-11e7-9ea0-7ad5080a30d3.PNG)

But the object returned just has an empty `pagination` array:
![missing_pagination_data](https://user-images.githubusercontent.com/183673/27835583-d951e268-60db-11e7-9a1f-9e9e8bac2d2c.PNG)

Any pointers how to debug this?

**Comment by vankasteelj** [comment]
I'll have to look into that, I have no problem with history syncing

**Comment by janpio** [comment]
First time I have tried `pagination:true`, so I am not sure if this is only this endpoint or all of them. (Checking...)

The current code is giving you a filled pagination object?

**Comment by janpio** [comment]
Yes, I have the same empty `pagination` object with `trakt.shows.popular({ pagination: true });`.

Hmm... 

(I am using the lib in an Angular context with polyfills, so maybe something is messy there... Will see if I can find out)

**Comment by vankasteelj** [comment]
![ark_2017-07-04_17-45-10](https://user-images.githubusercontent.com/12599850/27836629-8a4bfd8e-60e0-11e7-9f39-b9266dac81c8.png)

works fine for me

edit: and it's not linked to my engine, because both pure node in console and nwjs are giving the same results.
![mintty_2017-07-04_17-52-15](https://user-images.githubusercontent.com/12599850/27836847-82756392-60e1-11e7-99a0-e9a6373f8cc5.png)

**Comment by vankasteelj** [comment]
Here's where it's done : https://github.com/vankasteelj/trakt.tv/blob/master/trakt.js#L222

see if you can debug it, maybe `console.log(response.headers)` in there?

**Comment by janpio** [comment]
I did a `console.log(response)`:
![image](https://user-images.githubusercontent.com/183673/27837013-51b64734-60e2-11e7-9f05-ad8544f8b5f9.png)

Actual headers:
![image](https://user-images.githubusercontent.com/183673/27836986-312bd8bc-60e2-11e7-9e5f-45551e21c0ed.png)

This is strange.

**Comment by vankasteelj** [comment]
indeed, something is killing the headers

**Comment by janpio** [comment]
Should all of them be in there?

(Googling for "got headers missing" is great...)

**Comment by vankasteelj** [comment]
well, yes : 
![nw_2017-07-04_18-10-11](https://user-images.githubusercontent.com/12599850/27837353-079ef522-60e4-11e7-9797-0c76839b2d51.png)

maybe you have some sort of sanitizer or somthing sandboxing your requests between what is the actual response and what the app actually sees?

**Comment by janpio** [comment]
I have no idea - pretty new to all of this.
I am using your library in an Angular 4 / Ionic project that is run in the browser. The `http` (or whatever `got` uses in the background to actually make the request) is probably offered by a polyfill so that it works in the browser. Maybe there something goes wrong... A bit flustered on how to go on debugging this now. Looking at the `got` sourcecode right now :p

**Comment by vankasteelj** [comment]
modifying the _call() function to make it use not got and see if it changes anything shouldnt be too hard

**Comment by vankasteelj** [comment]
something like : 

```
var request = new XMLHttpRequest();

request.open('GET', 'https://api.trakt.tv/movies/tron-legacy-2010/lists');

request.setRequestHeader('Content-Type', 'application/json');
request.setRequestHeader('trakt-api-version', '2');
request.setRequestHeader('trakt-api-key', 'YOUR CLIENT ID');

request.onreadystatechange = function () {
  if (this.readyState === 4) {
    console.log('Status:', this.status);
    console.log('Headers:', this.getAllResponseHeaders());
    console.log('Body:', this.responseText);
  }
};

request.send();
```

here's what i get:
![nw_2017-07-04_18-21-31](https://user-images.githubusercontent.com/12599850/27837627-9e204e82-60e5-11e7-9ef7-3fa426dcea62.png)

**Comment by janpio** [comment]
You knew what I was googling while I was doing it ;)

Strangely identical output:
![image](https://user-images.githubusercontent.com/183673/27837886-5c510f44-60e7-11e7-8871-88d28481a36b.png)

(Now also tested in Firefox to make sure it is not Chrome messing with the headers)

(At least this is now much easier to google)

**Comment by janpio** [comment]
There we have the culprit: CORS once again.
https://www.w3.org/TR/cors/#simple-response-header

**Comment by janpio** [comment]
There seems to exist a server side solution (meh):
https://stackoverflow.com/a/22718272/252627

**Comment by janpio** [comment]
I noticed that the Trakt API currently responds to the preflight requests with this header already:
`access-control-allow-headers:Content-type, Authorization, Accept, trakt-api-key, trakt-api-version`

Seems this is because the request also requested these:
`access-control-request-headers:content-type,trakt-api-key,trakt-api-version`

`access-control-request-headers` seems to be filled with the headers you try to send with your request, so I added the `x-...` ones in you library.

Now it also requests them from the server:
`access-control-request-headers:content-type,trakt-api-key,trakt-api-version,x-pagination-item-count,x-pagination-limit,x-pagination-page,x-pagination-page-count`

Unfortunately the `access-control-allow-headers` response doesn't change 👎

**Comment by janpio** [comment]
Ok, definitely not this library's fault then. I will post in the trakt API Google group to get this solved somehow. Thanks for the help!

**Comment by janpio** [comment]
And here it is: https://plus.google.com/communities/103111515647012208243
(This might possibly require a change to the library in the end - I will submit a PR then)
