### ISSUE TITLE
Activate `pagination` globally so all (data) methods return {data:[...],pagination} instead of [...]

### ISSUE THREAD

**Issue by janpio** [vankasteelj/trakt.tv#31]
I think it would be neat to have a option to activate pagination for all calls so that they all return the data in a `data` key. Right now I have to work with `result` for some, and `result.data` for the ones where I explicitly sent in `pagination:true`.

(If paginatin is not supported it could be set to `null`.)

**Comment by vankasteelj** [comment]
In the readme, about pagination : 

> Note: this will contain data and pagination for all calls, even if no pagination is available. it's typically for really advanced use only

if you manually add pagination:true to any call, it should always send back `{data:[], pagination:{}}`, but there is no "global" option indeed. 

Can you first confirm that if you manually add `pagination:true` to all call, you do have an answer with `result.data` and no `result` only? If that works (it should) then making a global option will be easy

**Comment by vankasteelj** [comment]
@janpio please test dev branch

**Comment by janpio** [comment]
Wasn't active on the project in the last few weeks. I will let you know when I tried this.
