### ISSUE TITLE
[low priority] Experimental trakt.tv-cached plugin

### ISSUE THREAD

**Issue by ghost** [vankasteelj/trakt.tv#43]
So, just to see if I could, I made a plugin that automatically caches any GET call your module fires. It ended up very small and simple (90 lines), but it depends on your internal _construct function, which I'm sure is some kind of bad.

Do you think it would be a good idea to unleash this on the public? If the dependency on an internal, private piece of code is likely to break too easily I don't think I should release it.

There's no point talking about this before you have looked at the code and I'm sure you're busy, so take your time (or close the issue if you're not interested, it's OK).

https://github.com/MySidesTheyAreGone/trakt.tv-cached

Thanks!

**Comment by vankasteelj** [comment]
the plugin system was made to ease the hack of the main module, I don't see why this would be bad if released to the public, although you might need to specify somewhere in the readme that it needs to be up to date, or something like that. Just precaution, and maybe try to follow versionning (I only bump major release when I make breaking changes)

In 2 years, very few changes have been made to the _construct call, I don't see (yet?) why it would change any time soon^^

I've just looked at the code though, I havent tested it. The _construct code is indeed almost the one 'key' function of the module that gets fired at every require(), so you have to be sure it works. But apart from that, I don't see any issue.

**Comment by vankasteelj** [comment]
note: it's no longer a requirement to have `trakt.tv-<plugin>` kind of name since v4

**Comment by ghost** [comment]
Eh, I like the name. It makes the dependency clear right from the start. OK then, I'll move on to testing and fleshing it out! Thanks, I really needed your opinion on this. No need to keep this issue open, I'll let you know when the plugin is ready. It's probably going to come in handy for small apps that don't need their own caching system.

**Comment by ghost** [comment]
@vankasteelj 

trakt.tv-cached:
https://github.com/MySidesTheyAreGone/trakt.tv-cached

trakt.tv-queued:
https://github.com/MySidesTheyAreGone/trakt.tv-queued

I'll be testing them for a week or so, polish whatever needs polishing, finish writing the READMEs. They're looking good-ish.

**Comment by vankasteelj** [comment]
the queued is a good idea too, i might even use it for background calls, like library filling or such :)

**Comment by vankasteelj** [comment]
once they are published (with the right version number to match the main module, that would be good), PR to add to the docs those modules

**Comment by ghost** [comment]
Oh if you want to try it on something experimental you already can, I published a 0.1.something version. I should do a 1.0 release around next Monday, I'll open the PR shortly after.
