### ISSUE TITLE
Module not found: Can't resolve.. when adding to angular project

### ISSUE THREAD

**Issue by amritzz** [vankasteelj/trakt.tv#47]
Hi,

I am trying add this package to my angular 4 project and when I try to initialize the trakt const with options I get the following error:

ERROR in ./node_modules/trakt.tv/node_modules/got/index.js
Module not found: Error: Can't resolve './package' in 'C:\clientApp\node_modules\trakt.tv\node_modules\got'

Any help would be appreciated, thanks

**Comment by vankasteelj** [comment]
sounds like an issue with https://github.com/sindresorhus/got, on https://github.com/sindresorhus/got/blob/e31282dfd3402e7581bc7921746a62b35e9a8a31/index.js#L27 please ask there, I can't do much for you here :/
