### ISSUE TITLE
Docs on how to do Auth process

### ISSUE THREAD

**Issue by viniciusbig** [vankasteelj/trakt.tv#51]
Can you provide examples of how to handle authentication with this library?

I'm trying to make a node cli script so, my ideia is to have token store in a temp folder.

So, I thought about asking you some examples on how to handle authentication, the device mode, and how to store and restore the token. 

Thanks, in advance!

**Comment by viniciusbig** [comment]
Jean recommended the following link as examples on how to authenticate

[https://github.com/vankasteelj/frak/blob/master/app/js/lib/trakt.js](https://github.com/vankasteelj/frak/blob/master/app/js/lib/trakt.js)
and 
[https://github.com/butterproject/butter-desktop/blob/xaiki/react/src/app/lib/providers/trakttv.js](https://github.com/butterproject/butter-desktop/blob/xaiki/react/src/app/lib/providers/trakttv.js)

**Comment by viniciusbig** [comment]
I've come up with an code that get the Token and store it in a JSON file.
In the subsequent calls, It will try to get the token to be used.

https://gist.github.com/viniciusbig/e86cd43b28be5ea8e22c333e851f740d

**Comment by vankasteelj** [comment]
Closing as this will still appear in search
