### ISSUE TITLE
"Got"error: Right-hand side of 'instanceof' is not an Object

### ISSUE THREAD

**Issue by scott-buchanan** [vankasteelj/trakt.tv#53]
When calling the method trakt.users.history(*username*) I get this error:

`Unhandled Rejection (TypeError): Right-hand side of 'instanceof' is not an object`

Which led me to line 221 of trakt.js. After searching on google I found this:

https://github.com/sindresorhus/got/issues/693

The devs said you're basically SOL if using a browser and suggested perhaps https://github.com/sindresorhus/ky is a better solution. 

Thanks

**Comment by vankasteelj** [comment]
`Trakt.users.history({username:'justin'}).then(console.log).catch(console.log)` works for me:

```
0: {id: 4632956203, watched_at: "2019-07-09T02:25:12.000Z", action: "checkin", type: "episode", episode: {…}, …}
1: {id: 4631971739, watched_at: "2019-07-08T19:05:22.000Z", action: "checkin", type: "movie", movie: {…}}
2: {id: 4630525027, watched_at: "2019-07-08T03:35:14.000Z", action: "checkin", type: "episode", episode: {…}, …}
3: {id: 4623318694, watched_at: "2019-07-06T02:13:45.000Z", action: "scrobble", type: "movie", movie: {…}}
4: {id: 4618602937, watched_at: "2019-07-04T03:27:00.000Z", action: "scrobble", type: "episode", episode: {…}, …}
5: {id: 4618457111, watched_at: "2019-07-04T02:39:03.000Z", action: "checkin", type: "episode", episode: {…}, …}
6: {id: 4617707746, watched_at: "2019-07-03T19:18:11.000Z", action: "scrobble", type: "episode", episode: {…}, …}
7: {id: 4615997491, watched_at: "2019-07-03T02:50:13.000Z", action: "scrobble", type: "episode", episode: {…}, …}
8: {id: 4615886765, watched_at: "2019-07-03T02:15:37.000Z", action: "checkin", type: "episode", episode: {…}, …}
9: {id: 4615257070, watched_at: "2019-07-02T21:17:21.000Z", action: "checkin", type: "episode", episode: {…}, …}
length: 10
```

Using node.js

**Comment by vankasteelj** [comment]
Closing as this is "Trakt.tv API wrapper for Node.js", not for browsers

**Comment by vankasteelj** [comment]
You may PR an entire rewrite with something else than got, but it has to be based on promise and it cannot change the entire codebase of trakt.tv (for maintenance and support from me)
