### ISSUE TITLE
Search requires encodeURIComponent

### ISSUE THREAD

**Issue by edemaine** [vankasteelj/trakt.tv#57]
Minor issue:
```js
trakt.search.text({type: 'show', query: '3%'})
```
(and many other searches with special characters) cause exceptions.  An easy workaround is
```js
trakt.search.text({type: 'show', query: encodeURIComponent('3%')})
```
In my opinion, this type of encoding should be done by the library. But it wouldn't be backwards-compatible.

**Comment by vankasteelj** [comment]
You're right
