### ISSUE TITLE
Sanitizer parses special characters as entities

### ISSUE THREAD

**Issue by Migushthe2nd** [vankasteelj/trakt.tv#58]
Because sanitizer's sanitize function is used, special characters e.g. `&` in strings `title`, `overview`, `tagline` etc. are parsed as entity `&amp;`. This requires parsing these strings manually in my application.

**Comment by Migushthe2nd** [comment]
Yes I can, ofcourse, disable the sanitizer manually, but I'm just not sure sanitizer is intended to parse those characters as entities.

**Comment by vankasteelj** [comment]
i'm wondering if sanitizer is useful with https. I mean, if someone MIM something, you're in pretty bad shape already
