### ISSUE TITLE
Authorization example

### ISSUE THREAD

**Issue by nkamenar** [vankasteelj/trakt.tv#61]
I am trying to write a background service with node.js that monitors a folder on my computer and updates my Trakt collection when movies/shows are added to the folder? The documentation for how to authenticate seems to list a couple versions where you have to manually open a web page and jump through a bunch of hoops to get authorized but isn't there a simple way to just get a bearer token purely in code with no browser involved? Been searching all over the place but can't seem to find an example anywhere, thanks.

**Comment by nkamenar** [comment]
For some extra context this is what I have so far and I feel like it should work but I just keep getting a 405 when I try to request my movie collection. What am I missing here?

```
const traktAuth = new Trakt({
    client_id: 'MY_APP_ID',
    client_secret: 'MY_APP_SECRET',
});

const authResult = await traktAuth
    .get_codes()
    .then(poll => {
        process.stdout.write(JSON.stringify(poll) + '\n'); // printed to the console so I can authenticate with code in browser
        return traktAuth.poll_access(poll);
    })
    .catch(_ => {
        process.stderr.write('Time ran out for authentication\n');
        process.exit(1);
    });

const trakt = new Trakt({
    client_id: 'SAME_AS_ABOVE',
    client_secret: 'SAME_AS_ABOVE',
    access_token: authResult.access_token,
});

const results = await trakt.users.collection({
    username: 'MyTraktUserName',
    type: 'movie',
});
process.stdout.write(JSON.stringify(results, null, 2));
```

**Comment by vankasteelj** [comment]
> I am trying to write a background service with node.js that monitors a folder on my computer and updates my Trakt collection when movies/shows are added to the folder? The documentation for how to authenticate seems to list a couple versions where you have to manually open a web page and jump through a bunch of hoops to get authorized but isn't there a simple way to just get a bearer token purely in code with no browser involved? Been searching all over the place but can't seem to find an example anywhere, thanks.

Trakt uses OAuth2 https://trakt.docs.apiary.io/#reference/authentication-oauth. So no, as far as I can tell, there is no way to avoid user interaction, be it "device" or "browser" identification method.

**Comment by vankasteelj** [comment]
For your code, you are not using the correct `type`. https://trakt.docs.apiary.io/#reference/users/collection/get-collection shows the two possible values are `movies` or `shows`.
