### ISSUE TITLE
Optional parameters example?

### ISSUE THREAD

**Issue by amilajack** [vankasteelj/trakt.tv#7]
I think it would be good to add an example to the readme.md  of how to pass optional parameters:

``` javascript
// ...

let movieId = 'inception-2010'

trakt.movies.summary({
   id: movieId
})
```

**Comment by amilajack** [comment]
Also, is it possible to use this API to get a magnet url for a movie?

**Comment by vankasteelj** [comment]
Everything is [described on the wiki](https://github.com/vankasteelj/trakt.tv/wiki/Supported-methods), and no, there is nothing linking to illegal content here, trakt is a website (visit: https://trakt.tv/) that allows you to manage your viewings, collection, watchlist and all that. Kind of IMDB, if you want, but with nicer layout and more options to customize how you watch media, but not official. Trakt relies on its community for ratings and comments, and on open, crowdsourced external apis like tvdb, omdb and what's not for metadata
